name: proof_of_concept
version: 1.0.0+1
description: Proof of Concept Flutter application for the Swipe your Job startup.

publish_to: 'none'

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/img/branding/
    - assets/img/cards/